-- ========== 1. CRÉATION DES TABLES ==========

-- 1. Table Utilisateurs (Liée à auth.users de Supabase)
CREATE TABLE IF NOT EXISTS public.utilisateurs (
    id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
    nom TEXT NOT NULL,
    email TEXT UNIQUE NOT NULL,
    telephone TEXT,
    role TEXT NOT NULL CHECK (role IN ('admin', 'visiteur')) DEFAULT 'visiteur',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Fonction de Trigger pour insérer automatiquement dans 'utilisateurs' lors d'un signup
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS trigger AS $$
BEGIN
  INSERT INTO public.utilisateurs (id, nom, email, telephone, role)
  VALUES (
    new.id,
    COALESCE(new.raw_user_meta_data->>'nom', split_part(new.email, '@', 1)),
    new.email,
    COALESCE(new.raw_user_meta_data->>'telephone', ''),
    'visiteur'
  );
  RETURN new;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Exécution du trigger sur la table raw auth.users
DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE PROCEDURE public.handle_new_user();

-- 2. Table Artistes & Réalisateurs
CREATE TABLE IF NOT EXISTS public.artistes_realisateurs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nom TEXT NOT NULL,
    biographie TEXT,
    photo_url TEXT,
    pays TEXT,
    type TEXT CHECK (type IN ('Humoriste', 'Réalisateur', 'Autre', 'Direction FESTICO', 'Coordinateur', 'Candidate Miss', 'Candidat Film', 'Candidat Humour', 'Refusé')),
    email TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 3. Table Événements
CREATE TABLE IF NOT EXISTS public.evenements (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    titre TEXT NOT NULL,
    description TEXT,
    artiste_id BIGINT REFERENCES public.artistes_realisateurs(id) ON DELETE SET NULL,
    type TEXT CHECK (type IN ('Film', 'Humour', 'Atelier', 'Autre')),
    date_heure TIMESTAMP WITH TIME ZONE NOT NULL,
    lieu TEXT NOT NULL,
    prix_fcfa INTEGER NOT NULL DEFAULT 0,
    places_totales INTEGER NOT NULL,
    places_restantes INTEGER NOT NULL,
    image_url TEXT,
    est_publie BOOLEAN DEFAULT false,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 4. Table Commandes
CREATE TABLE IF NOT EXISTS public.commandes (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    utilisateur_id UUID REFERENCES public.utilisateurs(id) ON DELETE CASCADE,
    montant_total INTEGER NOT NULL,
    statut TEXT CHECK (statut IN ('en_attente', 'confirmee', 'annulee')) DEFAULT 'en_attente',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 5. Table Paiements
CREATE TABLE IF NOT EXISTS public.paiements (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    commande_id UUID UNIQUE REFERENCES public.commandes(id) ON DELETE CASCADE,
    methode TEXT CHECK (methode IN ('MTN Mobile Money', 'Orange Money', 'Carte', 'Autre')),
    reference_operateur TEXT UNIQUE,
    statut TEXT CHECK (statut IN ('en_attente', 'reussi', 'echoue')) DEFAULT 'en_attente',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 6. Table Billets
CREATE TABLE IF NOT EXISTS public.billets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    commande_id UUID REFERENCES public.commandes(id) ON DELETE CASCADE,
    evenement_id BIGINT REFERENCES public.evenements(id) ON DELETE CASCADE,
    code_qr TEXT UNIQUE NOT NULL,
    statut_scan BOOLEAN DEFAULT false,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);


-- ========== 2. INSERTION DES DONNÉES FACTICES ==========

-- =====================================================
-- Insertion de l'équipe de direction du FESTICO (données extraites du dossier officiel)
-- =====================================================
INSERT INTO public.artistes_realisateurs (nom, biographie, photo_url, type) VALUES
('Ferdinand Sylvère ENGO', 'Délégué général du Festico.', NULL, 'Direction FESTICO'),
('Kevine Islavia KEMAJOU', 'Directrice déléguée du Festico.', NULL, 'Direction FESTICO'),
('Lauriane AMOUGOU', 'Chargée du marketing et des relations publiques au festico.', NULL, 'Direction FESTICO'),
('Rosine ASSOGO', 'Chargée de la communication et coordinatrice de l''activité MiSS FESTICO.', NULL, 'Direction FESTICO'),
('Madeleine ABA', 'Correspondante du Festico en Europe.', NULL, 'Direction FESTICO'),
('Sandrine ELONO', 'Coordinatrice des activités du festico à paris / France.', NULL, 'Direction FESTICO'),
('Léonie Flore SIMO FOTSO', 'Coordonnatrice des activités du Festico à Douala.', NULL, 'Coordinateur'),
('Etienne NGOMANGA', 'Coordonnateur des activités du festico à Kribi.', NULL, 'Coordinateur');

-- =====================================================
-- Insertion de Candidatures Test (Miss FESTICO et Projets)
-- =====================================================
INSERT INTO public.artistes_realisateurs (nom, biographie, type, pays, photo_url) VALUES
('Amina Diallo', 'Étudiante en communication, passionnée par le théâtre et l''art culinaire.', 'Candidate Miss', 'Cameroun', 'https://images.unsplash.com/photo-1531123897727-8f129e1b28ce?auto=format&fit=crop&q=80'),
('Sarah Ndongo', 'Modèle photo et militante pour l''éducation des jeunes filles.', 'Candidate Miss', 'Cameroun', 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&q=80'),
('Jean Yves', 'Projet de court-métrage: "Le taxi fou de Bonamoussadi". Lien: youtube.com/watch... Synopsis: L''histoire d''un taximan...', 'Candidat Film', 'Cameroun', NULL);
INSERT INTO public.artistes_realisateurs (nom, biographie, type, pays) VALUES
('Gohou Michel', 'Légende de la comédie ivoirienne.', 'Humoriste', 'Côte d''Ivoire'),
('Moustik Karismatik', 'Humoriste emblématique du Cameroun.', 'Humoriste', 'Cameroun');

-- Insertion des événements
INSERT INTO public.evenements (titre, description, artiste_id, type, date_heure, lieu, prix_fcfa, places_totales, places_restantes, image_url, est_publie) VALUES
('Soirée d''Ouverture: Le Rire au Sommet', 'Inauguration du FESTICO 2026 avec la crème de la comédie africaine et un grand show.', (SELECT id FROM artistes_realisateurs WHERE nom='Moustik Karismatik' LIMIT 1), 'Humour', '2026-06-23 18:00:00+01', 'Hôtel de ville de Yaoundé (Esplanade)', 0, 500, 500, 'https://images.unsplash.com/photo-1514525253161-7a46d19cd819?auto=format&fit=crop&q=80', true),
('Masterclass: Comédie & Digital', 'Atelier sur comment utiliser les réseaux sociaux pour l''éducation via l''humour.', NULL, 'Atelier', '2026-06-24 10:00:00+01', 'Hôtel de ville (Salle des Actes)', 5000, 100, 100, 'https://images.unsplash.com/photo-1475721025505-c31516200ceb?auto=format&fit=crop&q=80', true),
('Gala de l''Humour avec Gohou', 'Spectacle exclusif payant avec Gohou Michel. Réservation obligatoire.', (SELECT id FROM artistes_realisateurs WHERE nom='Gohou Michel' LIMIT 1), 'Humour', '2026-06-26 20:00:00+01', 'Palais des Congrès', 10000, 1500, 1500, 'https://images.unsplash.com/photo-1507676184212-d0330a156520?auto=format&fit=crop&q=80', true);


-- ========== 3. CONFIGURATION RLS (Row Level Security) ==========
-- Pour que l'application frontend puisse lire les données
ALTER TABLE public.evenements ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.artistes_realisateurs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.utilisateurs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.commandes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.billets ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.paiements ENABLE ROW LEVEL SECURITY;

-- Autoriser la lecture publique de l'équipe et des events
CREATE POLICY "Lecture publique événements" ON public.evenements FOR SELECT USING (true);
CREATE POLICY "Lecture publique artistes" ON public.artistes_realisateurs FOR SELECT USING (true);

-- Utilisateurs: l'utilisateur modifie/lit sa propre ligne
CREATE POLICY "Lecture propre utilisateur" ON public.utilisateurs FOR SELECT USING (auth.uid() = id);
CREATE POLICY "Insert propre utilisateur" ON public.utilisateurs FOR INSERT WITH CHECK (auth.uid() = id);
-- Fonction permettant aux admins de lire toute la table (évite l'infinite recursion RLS)
CREATE OR REPLACE FUNCTION public.is_admin()
RETURNS BOOLEAN AS $$
DECLARE
  v_role TEXT;
BEGIN
  SELECT role INTO v_role FROM public.utilisateurs WHERE id = auth.uid();
  RETURN v_role = 'admin';
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE POLICY "Lecture de tous si admin" ON public.utilisateurs FOR SELECT USING ( public.is_admin() );

-- Commandes, Billets, Paiements : insertion/lecture pour l'user
CREATE POLICY "Commandes auth.uid" ON public.commandes FOR ALL USING (auth.uid() = utilisateur_id);
CREATE POLICY "Admin All Commandes" ON public.commandes FOR ALL USING ( public.is_admin() );

CREATE POLICY "Paiements All" ON public.paiements FOR ALL USING (true);
CREATE POLICY "Billets All" ON public.billets FOR ALL USING (true);

-- (Optionnel: Si on veut désactiver temporairement le RLS sur certaines tables pour que ça passe en dev)
-- ALTER TABLE public.billets DISABLE ROW LEVEL SECURITY;
-- ALTER TABLE public.commandes DISABLE ROW LEVEL SECURITY;
-- ALTER TABLE public.paiements DISABLE ROW LEVEL SECURITY;
-- ALTER TABLE public.utilisateurs DISABLE ROW LEVEL SECURITY;
-- ALTER TABLE public.evenements DISABLE ROW LEVEL SECURITY;
